library = {
    1: {"book_name": "To Kill a Mockingbird", "author_name": "Harper Lee", "quantity": 5},
    2: {"book_name": "1984", "author_name": "George Orwell", "quantity": 3},
    3: {"book_name": "The Great Gatsby", "author_name": "F. Scott Fitzgerald", "quantity": 7},
    4: {"book_name": "Pride and Prejudice", "author_name": "Jane Austen", "quantity": 10},
    5: {"book_name": "The Catcher in the Rye", "author_name": "J.D. Salinger", "quantity": 4},
    6: {"book_name": "The Lord of the Rings", "author_name": "J.R.R. Tolkien", "quantity": 6},
    7: {"book_name": "Harry Potter ", "author_name": "J.K. Rowling", "quantity": 8},
    8: {"book_name": "The Hobbit", "author_name": "J.R.R. Tolkien", "quantity": 3},
    9: {"book_name": "Animal Farm", "author_name": "George Orwell", "quantity": 5},
    10: {"book_name": "The Hunger Games", "author_name": "Suzanne Collins", "quantity": 9},
    11: {"book_name": "The Da Vinci Code", "author_name": "Dan Brown", "quantity": 2},
    12: {"book_name": "The Alchemist", "author_name": "Paulo Coelho", "quantity": 6},
    13: {"book_name": "The Fault in Our Stars", "author_name": "John Green", "quantity": 4},
    14: {"book_name": "Gone with the Wind", "author_name": "Margaret Mitchell", "quantity": 7},
    15: {"book_name": "The Chronicles of Narnia", "author_name": "C.S. Lewis", "quantity": 5},
    16: {"book_name": "The Sherlock Holmes", "author_name": "Arthur Conan Doyle", "quantity": 3},
    17: {"book_name": "A Game of Thrones", "author_name": "George R.R. Martin", "quantity": 6},
    18: {"book_name": "Brave New World", "author_name": "Aldous Huxley", "quantity": 4},
    19: {"book_name": "The Girl with the Dragon Tattoo", "author_name": "Stieg Larsson", "quantity": 2},
    20: {"book_name": "The Kite Runner", "author_name": "Khaled Hosseini", "quantity": 5},
    21: {"book_name": "The Road", "author_name": "Cormac McCarthy", "quantity": 3},
    22: {"book_name": "Wuthering Heights", "author_name": "Emily Brontë", "quantity": 6},
    23: {"book_name": "The Secret Garden", "author_name": "Frances Hodgson Burnett", "quantity": 4},
    24: {"book_name": "The Bell Jar", "author_name": "Sylvia Plath", "quantity": 2},
    25: {"book_name": "The Picture of Dorian Gray", "author_name": "Oscar Wilde", "quantity": 3},
    26: {"book_name": "The Count of Monte Cristo", "author_name": "Alexandre Dumas", "quantity": 7},
    27: {"book_name": "Moby-Dick", "author_name": "Herman Melville", "quantity": 5},
    28: {"book_name": "The Giver", "author_name": "Lois Lowry", "quantity": 4},
    29: {"book_name": "The Name of the Wind", "author_name": "Patrick Rothfuss", "quantity": 8},
    30: {"book_name": "Frankenstein", "author_name": "Mary Shelley", "quantity": 6},
    31:{"book_name":"varun","author_name":"varun","quantity": 5}
}
